spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  resources:
    static-locations:

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/simple_shop?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 11111111

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    properties:
#      hibernate:
#        id:
#          new_generator_mappings: false

#mybatis.config-location=classpath:mybatis-config.xml
#mybatis.mapper-locations=classpath:mappers/**/*.xml

simple-shop:
  file-upload:
    default-dir: /Users/psj/Desktop/SimpleShop/simple-shop-datacenter
#    default-dir: C:/Users/psj/Desktop/simple-shop-datacenter